export default {
    BOSS: "BOSS",
    STORAGE_MANAGER: "STORAGE-MANAGER",
    POSTOFFICE_MANAGER: "POSTOFFICE-MANAGER",
    STORAGE_EMMPLOYEE: "STORAGE-EMPLOYEE",
    POSTOFFICE_EMMPLOYEE: "POSTOFFICE-EMPLOYEE"
}